### ISSUE TITLE
burp 2024.2.1.2 报错

### ISSUE THREAD

**Issue by ykwiss** [vaycore/OneScan#23]
java.lang.IllegalArgumentException: collect directory not found.
	at burp.vaycore.onescan.manager.CollectManager.init(CollectManager.java:54)
	at burp.vaycore.onescan.common.Config.init(Config.java:82)
	at burp.BurpExtender.initData(BurpExtender.java:95)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:77)
	at burp.Zcbq.ZA(Unknown Source)
	at burp.Zm1l.ZJ(Unknown Source)
	at burp.Zm12.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by ykwiss** [comment]
已解决，本人电脑系统用户名为中文，配置文件路径存在中文导致， 把c盘默认路径的配置文件放到插件同目录下，把config.json中默认的路径修改为插件目录下的路径即可
